[package]
name = "dowser"
version = "0.3.6"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2021"
rust-version = "1.56"
description = "A multi-threaded, recursive file finding library for Unix."
license = "WTFPL"
repository = "https://github.com/Blobfolio/dowser"
readme = "README.md"
exclude = [
	".github",
	".gitignore",
	".righteous-sandbox.json",
	"about.toml",
	"doc",
	"examples",
	"justfile",
	"release",
	"tests",
]

[package.metadata.docs.rs]
features = [ "regexp" ]
default-target = "x86_64-unknown-linux-gnu"
targets = [ "x86_64-unknown-linux-gnu", "x86_64-apple-darwin" ]

[package.metadata.bashman]
name = "Dowser"
bash-dir = "./"
man-dir = "./"
credits-dir = "./"

[dependencies]
ahash = "0.7.*"
crossbeam-channel = "0.5.*"
rayon = "1.5.*"

[dependencies.parking_lot]
version = "0.12.*"
optional = true

[dev-dependencies]
brunch = "0.2.*"

[[bench]]
name = "dowser"
harness = false

[[bench]]
name = "extension"
harness = false

[features]
default = [ "parking_lot_mutex" ]

# Use parking_lot's Mutex instead of std's. The parking_lot version should be
# a bit faster in most cases, but does pull down a few extra dependencies.
parking_lot_mutex = [ "parking_lot" ]
