[package]
name = "dowser"
version = "0.2.4"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2021"
rust-version = "1.56"
description = "A multi-threaded, recursive file finding library for Unix."
license = "WTFPL"
repository = "https://github.com/Blobfolio/dowser"
readme = "README.md"
exclude = [
	".github",
	".gitignore",
	".righteous-sandbox.json",
	"about.toml",
	"doc",
	"examples",
	"justfile",
	"release",
	"tests",
]

[package.metadata.docs.rs]
features = [ "regexp" ]
default-target = "x86_64-unknown-linux-gnu"
targets = [ "x86_64-unknown-linux-gnu", "x86_64-apple-darwin" ]

[dependencies]
ahash = "0.7.*"
rayon = "1.5.*"

[dependencies.regex]
version = "1.5.*"
optional = true

[dev-dependencies]
brunch = "0.1.*"

[[bench]]
name = "dowser"
harness = false

[[bench]]
name = "dowser_filtered"
harness = false

[[bench]]
name = "extension"
harness = false

[features]
# Enable Regex matching in Dowser.
regexp = [ "regex" ]
